{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
{{- if .Values.grafana.ingress.annotations }}
{{ toYaml .Values.grafana.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.grafana.ingress.hostname }}"
      http:
        paths:
          - path: "{{ .Values.grafana.ingress.path }}"
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 4430
  tls:
    - hosts:
        - "{{ .Values.grafana.ingress.wildcardhostname }}"
      secretName: ""
{{- end }}