{{- if .Values.jmeterwiremock.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jmeterwiremock
  annotations:
{{- if .Values.jmeterwiremock.ingress.annotations }}
{{ toYaml .Values.jmeterwiremock.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.jmeterwiremock.ingress.hostname }}"
      http:
        paths:
          - path: "{{ .Values.jmeterwiremock.ingress.path }}"
            pathType: Prefix
            backend:
              service:
                name: jmeter-slaves-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - "{{ .Values.jmeterwiremock.ingress.wildcardhostname }}"
      secretName: ""
{{- end }}